name: Test actions
on: [push]

jobs:
  get-result:
    runs-on: ubuntu-latest
    name: Greet the user in Python
    steps:
      - name: Chechkout
        uses: actions/checkout@v4
      - name: Fetch result
        id: get_value
        uses: ./.github/actions/
        with:
          valor: "Judith"
      - name: Print result
        run: echo "${{ steps.get_value.outputs.result  }}"